project:
  type: book

book:
  title: "Conservation Biology"
  subtitle: "BI 328 | Fall 2024 | Saint Anselm College"
  author: "Shannon J. O'Leary"
  date: today 
  chapters:
    - index.qmd
    

    - part: A_stream-characterization.qmd
      chapters:
        - A01_watersheds.qmd
        - A02_USGSgages.qmd
        - A03_water-quality.qmd
        
    - part: B_stream-health-macroinverts.qmd
      chapters:
        - B01_bioindicators.qmd
        - B02_macro-diversity.qmd
        - B03_macro-indices.qmd

        
    - part: C_brook-trout.qmd
      chapters: 
         - C01_qPCR-evaluation.qmd
         - C02_brook-trout-occupancy.qmd
         - C03_thermal-regimes.qmd
         - C04_predicting-habiat-availability.qmd

    - part: D_set-up.qmd
      chapters:
        - D01_intro-R.qmd

bibliography: references.bib

format:
  html:
    theme: sandstone
    toc: true
    toc-depth: 2
    toc-location: left
    code-fold: false
    code-overflow: scroll
    code-copy: hover
    number-sections: true
    anchor-sections: true
    embed-resources: true
  pdf:
    documentclass: scrreprt
    
execute: 
  warning: false
  error: false

reference-location: margin
citation-location: margin
fig-cap-location: margin
tbl-cap-location: margin