# Exploring the hydrological, physical, and chemical charateristics of headwaters in the Piscataquog water shed {sec-characterize-headwaters}

For each of our units you will create a project folder that will contain an `Rproject` along with data, scripts, and other forms of documentation as we explore that topic, it will function as a digital lab notebook. At the beginning of the semester, you should have created a directory on your Desktop or Documents folder names `lb328` as a home directory^[We will use directory and folder synonymously throughout this lab notebook] for all of our projects this semester. 

Go ahead and create a subfolder called `01_watershed`, with folders called `data`, `results`, `scr`, and `reports` to hold various files you will access and create for this unit.

You will be able to download data sets and edit spreadsheets as we gather data from a [shared google folder here](https://drive.google.com/drive/folders/1APtt6Tp2nL56HqAnB1PYp31hSlpsIiNB?usp=sharing).

In this first unit, we will spend some time learning about watersheds, the importance of headwater streams, and characterizing various hydrological, physical, and chemical parameters to describe headwater streams in the Piscataquog watershed.




**After completing this unit you should be able to**

* Explain what a watershed is and describe its key components.
* Describe the potential vulnerabilities of watersheds, specifically due to anthropogenic effects and consider how they might differ across the watershed.
* Describe major categories of parameters that can be used to asses the ecosystem health of watersheds and headwater streams.
* Use mapping tools/GIS applications and other computational tools to explore publicly available data sets.
* Describe stream flow regimes using various types of data.
* Determine nutrient levels in stream water using standardized kits and place those values into context.
* Describe key components of thermal regimes and apply those to temperature data sets
* Feel more confident discussing, summarizing, and communicating your key findings with your peers and to the public



## Acknowledgements

Some of these activities borrow heavily the EDDIE Stream Discharge Module^[Bader, N.E., T. Meixner, C.A. Gibson, C.M. O'Reilly, and D.N. Castendyk. 26 June 2015. Project EDDIE: Stream Discharge. Project EDDIE Module 5, Version 2].