# Exploring brook trout occupancy in Piscataquog headwaters

For each of our units you will create a project folder that will contain an `Rproject` along with data, scripts, and other forms of documentation as we explore that topic, it will function as a digital lab notebook. At the beginning of the semester, you should have created a directory on your Desktop or Documents folder names `lb328` as a home directory^[We will use directory and folder synonymously throughout this lab notebook] for all of our projects this semester. 

Go ahead and create a subfolder called `03_brook-trout`, with folders called `data`, `results`, `scr`, and `pubs` to hold various files you will access and create for this unit.

You will be able to download data sets and edit spreadsheets as we gather data from a [shared google folder here](https://drive.google.com/drive/folders/16XJHELFL5EnQRO_OZhz8z1gqdhJlgxtF?usp=drive_link).


In this third unit, we use a species specific qPCR assay to determine whether brook trout are using Rand Brook as habitat. We will also dig into the paired air and water temperature monitoring data to assess whether headwater streams have the potential to serve as climate refugia for cold-water fishes such as brook trout.

The research objectives for this component of our headwater monitoring project is to 

1. Identify headwater streams serving as brook trout habitat during summer months.
2. Use long-term temperature data to identify thermal regimes of headwater streams and assess their future potential brook trouth habitat potential.


**Learning Objectives**

After completing this activity you should be able to

* Describe how eDNA is emerging as a valuable biomonitoring tool.
* Interpret qPCR results.
* Describe the thermal regime of a stream using a wide range of metrics to determine the magnitude, frequency, duration, rate of change, timing, and variability of temperature and chose an appropriate metric to answer a specific biological/ecological question.
